recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import login_view, logout_view, logout_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('logout_success', logout_success, name='logout_success'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeDetailView
from .views import RecipeListView
from .views import search_view
from .views import add_recipe

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', search_view, name='search'),
    path('list/add/', add_recipe, name='add_recipe'),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    # class attributes
    recipe_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    ingredients = models.CharField(
        max_length=225,
        help_text="Enter the ingredients, separated by a comma"
    )
    cooking_time = models.IntegerField(help_text="Enter cooking time in minutes")
    difficulty = models.CharField(max_length=20, blank=True)
    pic = models.ImageField(upload_to='recipes', default='no_picture')

    # determine recipe difficulty
    def calculate_difficulty(self):
        ingredients = self.ingredients.split(", ")
        if self.cooking_time < 10 and len(ingredients) < 4:
            return "Easy"
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            return "Medium"
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            return "Intermediate"
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            return "Hard"
        return "Unknown"

    # string representation
    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = (
    ('#1', 'Bar Chart'),
    ('#2', 'Pie Chart'),
    ('#3', 'Line Chart'),
)

# Define class-based form
class RecipeSearchForm(forms.Form):
    search_term = forms.CharField(max_length=200, required=False, label="Search Recipes")
    ingredients = forms.CharField(max_length=200, required=False)
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'cooking_time', 'ingredients', 'pic']

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            
            user=authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('recipes:list')
            
        else:
            error_message='oops.. something went wrong'
    
    context={
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('logout_success')

def logout_success(request):
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Recipe
# to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeSearchForm, RecipeForm
import pandas as pd
from .utils import get_recipename_from_id, get_chart
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/list.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'

@login_required
def search_view(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None
    chart = None

    # check if button is clicked
    if request.method =='POST':
        # search_term = request.POST.get('search_term')
        chart_type = request.POST.get('chart_type')
        
        # apply filter to extract data
        qs = Recipe.objects.filter()
        if qs:
            recipe_df=pd.DataFrame(qs.values())
            # recipe_df['Link'] = recipe_df.apply(lambda row: f'<a href="./detail.html?{row["recipe_id"]}" target="_blank">{row["name"]}</a>', axis=1)
            chart=get_chart(chart_type, recipe_df, labels=recipe_df['name'].values)
            recipe_df=recipe_df.to_html(escape=False)
        
    context={
        'form': form,
        'recipe_df': recipe_df,
        'chart': chart,
    }
        # load the search page
    return render(request, 'recipes/search.html', context)

@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipes:list')  # Redirect to the recipe list after saving
    else:
        form = RecipeForm()
    return render(request, 'add_recipe.html', {'form': form})

recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/detail.css' %}?v={{ STATIC_VERSION }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Details</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <h2>Details: {{object.name}}</h2>

    <b>Recipe: </b> {{object.name}} <br>

    <b>Ingredients: </b> {{object.ingredients}} <br>

    <b>Cooking Time: </b> {{object.cooking_time}} <br>

    <b>Difficulty: </b> {{object.calculate_difficulty}} <br>

    <img src="{{object.pic.url}}" width="350" height="300" alt="{{object.name}}" />
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

recipes/templates/recipes/list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/list.css' %}?v={{ STATIC_VERSION }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Recipe List</title>
</head>

<body>
  <div class="container">
    <h1>Recipes List</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <table border="1" cellpadding="5" cellspacing="5">
      <tr>
        <td style="font-size: 30px;"> Recipe Title</td>

        <td style="font-size: 30px;"> Recipe Image</td>
      </tr>
      {% for object in object_list %}
      <tr>
        <td><a href="{{object.get_absolute_url}}">
            {{object.name}}
          </a></td>
        <td><img src="{{object.pic.url}}" width="150" height="200" /> </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/recipes_home.css' %}?v={{ STATIC_VERSION }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="{% static 'recipes/js/home.js' %}"></script>
    <title>Recipes Home Page</title>
</head>


<body>
    <h1>
        Welcome to your Recipes
    </h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'login' %}">Login</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="welcome-pic">
        <img src="{% static 'recipes/images/welcomepage.jpg' %}" alt="recipes_home" width="1500" height="600">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/search.css' %}?v={{ STATIC_VERSION }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Search</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <h1>Search for recipes</h1>
  <hr>
  <div class="container">
    <form action="" method="POST">
      {%csrf_token %}
      {{form}}
      <button type="submit">Search</button>
    </form>
    <br>
    <div class="table">
      {% if recipe_df %}
      {{recipe_df|safe}}
      <br>
      <a href="{{object.get_absolute_url}}">
        {{object.name}}
      </a>
      <img src="data:image/png;base64, {{chart|safe}}">
      {% else %}
      <h3>No data</h3>
      {% endif %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

src/recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/detail.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Details</title>
</head>

<body style="background-color: white;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href = "{%url 'logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div style="background-color: #64c9e5;">
        <h2>Details: {{object.name}}</h2>

        <b>Recipe: </b> {{object.name}} <br>

        <b>Ingredients: </b> {{object.ingredients}} <br>

        <b>Cooking Time: </b> {{object.cooking_time}} <br>

        <b>Difficulty: </b> {{object.calculate_difficulty}} <br>

        <img src="{{object.pic.url}}" width="350" height="300" alt="{{object.name}}" />
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

src/recipes/templates/recipes/list.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/list.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Recipe List</title>
</head>

<body>
    <h1>Recipes List</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
                  </li>
              <li class="nav-item">
                <a class="nav-link" href = "{%url 'logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <table border="1" cellpadding="5" cellspacing="5">
        <tr>
            <td style="font-size: 30px;"> Recipe Title</td>

            <td style="font-size: 30px;"> Recipe Image</td>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><a href="{{object.get_absolute_url}}">
                    {{object.name}}
                </a></td>
            <td><img src="{{object.pic.url}}" width="150" height="200" /> </td>
        </tr>
        {% endfor %}
    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Recipes Home Page</title>
</head>

<body>
    <h1 style="text-align: center; font-size: 50px; font-family:'Times New Roman', Times, serif;">
        Welcome to your Recipes
    </h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'login' %}">Login</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <img src="{% static 'recipes/images/welcomepage.jpg' %}" alt="recipes_home" width="1875" height="800">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

src/recipes/templates/recipes/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Search</title>
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
                      </li>
                  <li class="nav-item">
                    <a class="nav-link" href = "{%url 'logout' %}">Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </div>
    <h1>Search for recipes</h1>
    <hr>
    <form action="" method="POST">
        {%csrf_token %}
        {{form}}
        <button type="submit">Search</button>
    </form>
    <br>
    {% if recipe_df %}
    {{recipe_df|safe}}
    <br>
    <a href="{{object.get_absolute_url}}">
        {{object.name}}
    </a>
    <img src="data:image/png;base64, {{chart|safe}}">
    {% else %}
    <h3>No data</h3>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

templates/add_recipe.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Recipes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .container {
            padding: 100px;
            background-color: #807ED9;
            text-align: center;
            width: 40%;
            margin: 20px auto;
            border-collapse: collapse;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .form-group label {
            font-weight: bold;
        }

        h1 {
            text-align: center;
            font-size: 50px;
            font-family: 'Times New Roman', Times, serif;
            color: #807ED9;
        }
        
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'recipes:list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'recipes:search' %}">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <h1> Add Recipes</h1>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Recipe Name:</label>
                <input type="text" name="name" class="form-control" id="id_name" required>
            </div>
            <div class="form-group">
                <label for="id_cooking_time">Cooking Time (minutes):</label>
                <input type="number" name="cooking_time" class="form-control" id="id_cooking_time" required>
            </div>
            <div class="form-group">
                <label for="id_ingredients">Ingredients:</label>
                <textarea name="ingredients" class="form-control" id="id_ingredients" rows="5" required></textarea>
            </div>
            <div class="form-group">
                <label for="id_picture">Picture:</label>
                <input type="file" name="pic" class="form-control-file" id="id_picture">
            </div>
            <button type="submit" class="btn btn-primary">Add Recipe</button>
        </form>
    </div>

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>